### ISSUE TITLE
Unable to extract access_token

### ISSUE THREAD

**Issue by heitzerj-grapes** [shubhamdipt/django-microsoft-authentication#12]
Hi!
For several days now this package stopped working. When running through the auth flow the following error is thrown.

```
support_backend_api    | Internal Server Error: /api/microsoft_authentication/callback
support_backend_api    | Traceback (most recent call last):
support_backend_api    |   File "/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
support_backend_api    |     response = get_response(request)
support_backend_api    |                ^^^^^^^^^^^^^^^^^^^^^
support_backend_api    |   File "/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
support_backend_api    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
support_backend_api    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
support_backend_api    |   File "/venv/lib/python3.11/site-packages/microsoft_authentication/views.py", line 32, in callback
support_backend_api    |     ms_user = get_user(result["access_token"])
support_backend_api    |                        ~~~~~~^^^^^^^^^^^^^^^^
support_backend_api    | KeyError: 'access_token'
```

On AAD side everything looks good, the login itself works fine.
Any idea why this is suddenly happening?

**Comment by bpshubhamdipt** [comment]
This generally happens if the settings have not been configured properly at the Azure level.

**Comment by shubhamdipt** [comment]
This generally happens if the settings have not been configured properly at the Azure level.

**Comment by heitzerj-grapes** [comment]
Nothing was actively changed either on the aad side or on the application side…it just randomly stopped working 🤷 .

When writing the comment it dawned on me…can now confirm there is nothing wrong with the package.
Simple case of expired app secret 🙈.

Sorry for the inconvenience!
